### ISSUE TITLE
App container gets killed if download fails

### ISSUE THREAD

**Issue by telphan** [resin-io/resin-supervisor#175]
If container download fails for a specific reason (e.g. 'Error pulling image (latest) from registry.resin.io/app/sha, ApplyLayer exit status 1 unexpected EOF') the app container will be killed and will wait for the download to retry and complete.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lfd)

**Comment by pcarranzav** [comment]
Note: this is only in the kill-then-download case

**Comment by lifeeth** [comment]
@pcarranzav In this case kill-then-download was not set.

**Comment by pcarranzav** [comment]
@telphan @lifeeth can we try to reproduce? I'd need to see in which conditions this happens, cause in the general case the app is only killed after the download has completed successfully.

**Comment by pcarranzav** [comment]
The only linked support conversation is a case when kill-then-download was set. Another possibility would be that the device was moved between apps, in which case the kill and download can happen in parallel. In both cases this would be expected behavior (except for the download failure of course) - so I'm closing this as we haven't seen any instances in more than a year where this is buggy behavior, and we'd need more information to investigate.
