### ISSUE TITLE
Provisioning may complete without writing to config.json

### ISSUE THREAD

**Issue by abresas** [resin-io/resin-supervisor#194]
A device had config partition mounted as read only, provisioning completed probably trying to write to config.json, but it never was able to.

Supervisor should not assume provisioning is complete if uuid is not written to config.json, because it is essential for vpn to function.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/L2luYm94ZXMvdG9waWNzLzIzMDIx)

**Comment by pcarranzav** [comment]
This is very weird, because seeing [this](https://github.com/resin-io/resin-supervisor/blob/master/src/bootstrap.coffee#L67) provisioning should not continue if the uuid wasn't written.
I think the write succeeded but somehow it didn't get synced to the card. But if the filesystem was read only, how did the `fs.writeFileAsync` go through without throwing?
