### ISSUE TITLE
Watchdog timer

### ISSUE THREAD

**Issue by iitgrad** [resin-io/resin-supervisor#234]
Would be great to able to set a timer such that if a docker image or OS hangs in some way, a reset is performed.  https://docs.docker.com/engine/reference/run/#/healthcheck

**Comment by pcarranzav** [comment]
This has been implemented in a variety of ways in https://github.com/resin-os/meta-resin - especially in https://github.com/resin-os/meta-resin/pull/928 - and also the supervisor has a healthcheck since #530. In resinOS, the balena container engine restarts containers that are marked as unhealthy, so users wanting their containers restarted if they're unhealthy get that too.
