### ISSUE TITLE
Omitting logs on reboot

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-supervisor#236]
If I reboot the device (via the api) it omits the first two logs of my app. 

Logs after a restart

```
21.08.16 20:23:58 [+0100] Starting application 'registry.resin.io/microbeastlondon/def087039ac902b6df73f527dca5754d002638a5'
21.08.16 20:24:00 [+0100] Started application 'registry.resin.io/microbeastlondon/def087039ac902b6df73f527dca5754d002638a5'
21.08.16 20:24:00 [+0100] rendering image
21.08.16 20:24:04 [+0100] using "DejaVu Sans Mono-16", pixelsize=16.67 file=/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
```

logs after a reboot 

```
21.08.16 20:25:21 [+0100] Starting application 'registry.resin.io/microbeastlondon/def087039ac902b6df73f527dca5754d002638a5'
21.08.16 20:25:31 [+0100] Started application 'registry.resin.io/microbeastlondon/def087039ac902b6df73f527dca5754d002638a5'
```

**Comment by shaunmulligan** [comment]
i noticed this a lot today on:
HOST OS VERSION
Resin OS 1.8.0
SUPERVISOR VERSION
1.13.0

I think its pretty easy to reproduce and seems to only happen with reboot but not restart app

**Comment by imrehg** [comment]
Run into this today, resulting in 20-30 seconds of missing logs on device boot. Used this project to reproduce: https://github.com/resin-io-playground/iterativelogs

**Comment by pcarranzav** [comment]
Yeah @shaunmulligan @imrehg this is due to the docker restart policy causing the app container to be started on boot before the supervisor is up. Not sure how we'd go about solving it until we refactor the logging system...

**Comment by Page-** [comment]
@pcarranzav is it possible to work around this if wanted by disabling the automatic docker restart policy?

**Comment by shaunmulligan** [comment]
@Page- i guess you are asking if users could set RESIN_APP_RESTART_POLICY = no?

**Comment by shaunmulligan** [comment]
@Page- are you saying we should have the default restart policy be "no" rather than it currently being "always" ? we can do that, but the nice thing about this, besides the fact that the logs are lost is that the users application starts quicker on reboot because it doesnt have to wait for the supervisor to start. The one other downside is that if their application logic uses the supervisor API, it needs to check that the supervisor is up before trying to do stuff.

**Comment by Page-** [comment]
No, I'm trying to find out if a user can choose to manually set that flag if they want/need the old behaviour, and hence have a way to avoid the issue of lost logs

**Comment by shaunmulligan** [comment]
Yeah I believe they can already do that

**Comment by shaunmulligan** [comment]
I can confirm that a user can set `RESIN_APP_RESTART_POLICY` = `no` and they will have the previous behaviour. I will note this in the new docs on App lifecycle, but we still need to retroactively fetch the logs either using `docker logs --since` or using `journalctl`. @petrosagg should we create a ticket somewhere to track that?
