### ISSUE TITLE
EAI_AGAIN error whilst trying to download

### ISSUE THREAD

**Issue by Page-** [resin-io/resin-supervisor#442]
Saw this error repeated over and over again in a device that failed to download, restarting the supervisor container fixed it
```
Error: getaddrinfo EAI_AGAIN api.resin.io:443
  at Object.exports._errnoException (util.js:1026:11)
  at errnoException (dns.js:33:15)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
code: 'EAI_AGAIN',
errno: 'EAI_AGAIN',
syscall: 'getaddrinfo',
hostname: 'api.resin.io',
host: 'api.resin.io',
port: 443
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1t8n)

**Comment by pcarranzav** [comment]
This is due to DNS errors that show up in some conditions:
* a docker-in-docker app that removes iptables rules used by resin OS to route DNS traffic.
* some other misconfiguration in the DNS settings.

If anyone sees this again, please send me leech output - I'm especially interested in /etc/resolv.conf inside the supervisor container, iptables rules and any other particularities about the network setup.

**Comment by pcarranzav** [comment]
Closing this since it's not really a supervisor bug, and it's due to a misconfiguration of DNS in the host OS.  Most instances of this should've been fixed in https://github.com/resin-os/meta-resin/pull/902

**Comment by majorz** [comment]
Just as a note to avoid confusion - it does not seemed fixed in the above meta-balena release. It was still occurring in on a Resin OS 2.13.6+rev1 device.
