### ISSUE TITLE
Dispose is removing the container lock?

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-supervisor#454]
I'm trying to figure out why the lockfile is not preventing updates with Resin Supervisor 4.1.1 on a 2.x os image.

I have confirmed the lock file exists in the right spot and that the lock override is not set. Yet the container keeps getting upgraded.

The line below appears to always clear the lock file after attempting the application.lockUpdates()
https://github.com/resin-io/resin-supervisor/blob/ac2531368c8c7fb11d5ce77a26a5e29bf026975c/src/application.coffee#L420

Note that even when my application running in a container applies the lock, we are still the root (0) user and the supervisor container has the rights to unlock the file without an exception occurring.

So am I reading this wrong, of will the 2nd polling attempt always succeed when there are pending updates because the container removed the lock when disposing after the first attempt?

**Comment by pcarranzav** [comment]
@BrianAdams that disposer shouldn't be called if the `throw new UpdatesLockedError` above is called (which is what happens when the file is there).
So there must be something else going on - would you pass me the link to the device for me to go in and investigate?
BTW, are you using an exclusive open to create the file? i.e. making sure the file is not there when you create it. ([docs](https://github.com/resin-io/resin-supervisor/blob/master/docs/update-locking.md#taking-the-lock))

**Comment by pcarranzav** [comment]
Closing this given the explanation above (the disposer isn't called when updates are locked). There's also been a lot of changes to the update locking system since the time this issue was filed - @BrianAdams let me know if you keep seeing this issue in supervisor 7.1.14, and if so, please confirm the method you're using to create the lockfile. Thanks!
