### ISSUE TITLE
Allow /v1/restart to restart single device

### ISSUE THREAD

**Issue by ajbeaven** [resin-io/resin-supervisor#597]
I'd like to use `/v1/restart` with a `uuid` to restart a single device but it appears that the endpoint expects an `appId`. Please add support for restarting a single device.

**Comment by pcarranzav** [comment]
@ajbeaven these endpoints all run in the supervisor on a single device, so they will not restart all the devices in the app but just the device on which the supervisor is running.

Specifying the appId is only necessary because the supervisor needs to know what app to restart.

If you look at the [docs](https://github.com/resin-io/resin-supervisor/blob/master/docs/API.md#post-v1restart) you'll see that  you can either call the endpoint from your container - in which case you'll restart the device in which this is running - or you can call it with through the resin API, in which case you *can* specify a uuid.

(All devices will restart only if you *don't* specify a uuid when calling it via the resin API)
