### ISSUE TITLE
Service variables get updated only after the device has fetched application update

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-supervisor#609]
We had a report that devices that come online and need to fetch an app update only fetch/apply service variables after the update has been completed.

Not sure if this is intended behaviour of the supervisor update state machine. We have also attached an support conversation for more context.

cc @pcarranzav @camerondiver

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ae3n)

**Comment by pcarranzav** [comment]
This is by design: when a device  has to run a new release, this becomes part of the device's target state. When env vars are added after that, they are also included in the target state. The supervisor is designed to apply the whole target state at once, and not to apply it partially which could potentially cause conflicts.
